name: Java Release

on:
  release:
    types: [published]

jobs:

  release:
    if: github.repository == 'PasteUs/PasteMeAdmin'
    name: Build on ${{ matrix.os }} and upload

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: username
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: pasteme
        ports:
          - 4399:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Build
        run: |
          mvn --settings .github/settings.xml \
              --file pom.xml \
              -Dspring.config.location=docker/config/application.yml \
              package

#      - name: Upload to release
#        uses: JasonEtco/upload-to-release@master
#        with:
#          args: pasteme-admin-jar.tar.gz application/octet-stream
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_PASSWORD }}

      - name: Publish Docker
        uses: LucienShui/Publish-Docker-Github-Action@2.7.1
        with:
          name: registry.cn-hangzhou.aliyuncs.com/pasteus/pasteme-admin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          dockerfile: Dockerfile
          tag_names: true
