name: Go Release

on:
  release:
    types: [published]

jobs:

  release:
    if: github.repository == 'PasteUs/PasteMeAdmin'
    name: Build with go ${{ matrix.go_version }} on ${{ matrix.os }} and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        go_version: [1.13]
        os: [ubuntu-latest]

    steps:

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          
      - name: Deploy to Github Package Registry
        run: |
          mvn --settings .github/settings.xml \
              --file pom.xml \
              -Dspring.config.location=docker/config/application.yml \
              package

#      - name: Upload to release
#        uses: JasonEtco/upload-to-release@master
#        with:
#          args: pasteme-admin-jar.tar.gz application/octet-stream
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_PASSWORD }}

      - name: Publish Docker
        uses: LucienShui/Publish-Docker-Github-Action@2.7.1
        with:
          name: registry.cn-hangzhou.aliyuncs.com/pasteus/pasteme-admin
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: registry.cn-hangzhou.aliyuncs.com
          dockerfile: Dockerfile
          tag_names: true
